title: Resume
description: Backend Engineer Resume
baseurl: "/da-nyee"
url: "https://da-nyee.github.io"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
