title: Resume
description: Software Engineer Resume
baseurl: ""
url: "https://lee-daeun.dev"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
